# Generated by Django 4.2.14 on 2024-07-18 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0002_userprofile_user_alter_userprofile_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Display_name',
            field=models.CharField(default=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=200, unique=True),
        ),
    ]
