# Generated by Django 4.2.14 on 2024-07-18 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile_page', '0003_alter_userprofile_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Display_name',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
