# Generated by Django 4.2.14 on 2024-07-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0004_remove_userprofile_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_url',
            field=models.SlugField(null=True),
        ),
    ]
